<template>
<section class="section containerPortada"><parallax class="contenedor-portada" :style="Image3"><aside id="left"><div class="md-size-50 md-small-size-70 md-xsmall-size-100 textoIntro imgMobile"><h1 class="title blanco">Discover, Collect <br/>and Play A Great Card Game </h1><h4>Built on the NEAR Blockchain</h4></div></aside><aside id="right"><div class="decoracionImg"><div class="img" :style="Image2"/></div></aside><aside id="bottom"><div class="botoncito"><md-tooltip class="tooltip" md-direction="top">Coming soon! </md-tooltip><md-button id="botonIntro" href="#" target="_blank"><span class="texto-boton">Login with Near</span></md-button></div></aside></parallax></section>
</template>

<script>
export default{data(){return{first:false};},props:{imagen:{type:String,default:require("@/assets/img/Img.png")},imagen2:{type:String,default:require("@/assets/img/Img2.png")},imagen3:{type:String,default:require("@/assets/img/fondoImg.png")}},computed:{Image(){return{backgroundImage:`url(${this.imagen})`};},Image2(){return{backgroundImage:`url(${this.imagen2})`};},Image3(){return{backgroundImage:`url(${this.imagen3})`};}}};
</script>

<style lang="scss" scoped>
.blanco{color:#fff !important}.texto-boton{color:#fff;font-weight:600;font-size:var(--step--1);text-transform:none !important}.botoncito{visibility:visible}#botonIntro{display:flex;justify-content:center;align-items:center;padding:30px;height:3.875rem;background:#a5a !important;border-radius:30px}.textoIntro h1{font-family:-apple-system,BlinkMacSystemFont,Arial,sans-serif !important;font-size:var(--step-6);font-weight:900;visibility:visible}.textoIntro h4{font-size:var(--step-1);font-weight:400 !important;visibility:visible}.imgMobile{background:center no-repeat;background-size:cover;width:auto;height:auto;border-radius:1em;z-index:2;visibility:hidden}.img{background:center no-repeat;background-size:cover;width:100%;height:100%;z-index:2}.decoracionImg{display:flex;align-items:center;justify-content:center;width:100%;height:27vmax;position:relative}.decoracionImg:after{content:"";position:absolute;width:27.07625rem;height:17.105625rem;left:0;right:0;bottom:0;background:#c9c;filter:blur(109.769px);transform:rotate(30deg)}
#left{grid-area:left;display:flex;align-items:center}#right{grid-area:right;width:100%;height:100%;display:flex;align-items:center;margin:auto 5%}#bottom{color:#fff;grid-area:bottom;display:flex;justify-content:flex-start}.containerPortada{padding-left:5%;padding-right:5%}.contenedor-portada{display:grid;grid-template-areas:"left right" "left right" "bottom bottom";grid-template-columns:55% 40%;border-radius:20px !important;padding-left:2vmax;padding-bottom:2vmax;background:center no-repeat;background-size:cover}.tooltip{background:#000 !important;backdrop-filter:blur(5px) !important;color:#fff !important}
</style>
